services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks: 
      - notes-app  
    depends_on:
      - django_app


  mysql:
    container_name: mysql
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db

    volumes: 
      - mysql-data:/var/lib/mysql
    networks:
      - notes-app  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  django_app:
    build:
      context: .
    container_name: django_cont
    ports: 
      - "8000:8000"
    env_file: 
      - ".env"  
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always
    networks:
      - notes-app  
    depends_on: 
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 


volumes:
  mysql-data:

networks:
  notes-app:

